//Generated by FigmaQML 3.1.0

import Qt5Compat.GraphicalEffects
import QtQuick
import QtQuick.Shapes
import FigmaQmlInterface
Rectangle {
// component (Instance) level: 0 Button 
    id: figma_1_23
    // # "Button"
    objectName:"Button"
    x:0
    y:0
    width:113
    height:45
    color: "transparent"
    clip: false 
    Component.onCompleted: {
    }
}
