//Generated by FigmaQML 3.1.0

import Qt5Compat.GraphicalEffects
import QtQuick
import QtQuick.Shapes
import FigmaQmlInterface
Rectangle {
// component (Instance) level: 0 qml?server_address.onClick 
    id: figma_3_96
    // # "qml?server_address.onClick"
    objectName:"qml?server_address.onClick"
    MouseArea {
        anchors.fill: parent
        onClicked: { FigmaQmlSingleton.eventReceived( 'server_address', 'click_event' ); }
        onPositionChanged: { FigmaQmlSingleton.eventReceived( 'server_address', 'mouse_move_event' ); }
        onPressAndHold: { FigmaQmlSingleton.eventReceived( 'server_address', 'press_and_hold_event' ); }
        onDoubleClicked: { FigmaQmlSingleton.eventReceived( 'server_address', 'double_clicked_event' ); }
        onPressed: { FigmaQmlSingleton.eventReceived( 'server_address', 'pressed_event' );}
        onReleased: { FigmaQmlSingleton.eventReceived( 'server_address', 'released_event' ); }
    }
    x:0
    y:0
    width:263
    height:49
    color: "transparent"
    clip: false 
    Component.onCompleted: {
    }
}
