//Generated by FigmaQML 3.0.3

import Qt5Compat.GraphicalEffects
import QtQuick
import QtQuick.Shapes
import FigmaQmlInterface
Rectangle {
// component (Instance) level: 0 qml?server_address.onClick 
    id: figma_3_96
    // # "qml?server_address.onClick"
    objectName:"qml?server_address.onClick"
    MouseArea {
        anchors.fill: parent
        onClicked: { FigmaQmlSingleton.eventReceived( 'server_address', 'click_event' ); }
    }
    x:0
    y:0
    width:263
    height:49
    color: "transparent"
    clip: false 
    Component.onCompleted: {
    }
}
