//Generated by FigmaQML 3.0.3

import Qt5Compat.GraphicalEffects
import QtQuick
import QtQuick.Shapes
import FigmaQmlInterface
Rectangle {
// component (Instance) level: 0 Subscribe 
    id: figma_3_110
    // # "Subscribe"
    objectName:"Subscribe"
    x:0
    y:0
    width:309
    height:599
    color: "transparent"
    clip: true 
    Rectangle {
    // component (Instance) level: 0 Subscribe 
        id: figma_3_58
        // # "Subscribe"
        objectName:"Subscribe"
        x:0
        y:0
        width:309
        height:599
        color: "transparent"
        clip: false 
        Shape {
        // component (Instance) level: 0 Rectangle 1 
            id: figma_3_59
            // # "Rectangle 1"
            objectName:"Rectangle 1"
            x:0
            y:0
            width:309
            height:599
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ffe24747"
                // component (shapeFill) level: 0 
                id: svgpath_figma_3_59
                fillRule: ShapePath.WindingFill
                PathSvg {
                    id: path_0_figma_3_59
                    path: "M0 0L309 0L309 599L0 599L0 0Z"
                } 
            }
        property alias path: path_0_figma_3_59.path
        }
        Text {
        // component (Instance) level: 0 QMQTTI 
            id: figma_3_66
            // # "QMQTTI"
            objectName:"QMQTTI"
            x:24
            y:14
            width:159
            height:38
            color:"#ff000000"
            wrapMode: TextEdit.WordWrap
            text:"QMQTTI"
            font.family: "DejaVu Sans"
            font.italic: false
            font.letterSpacing: 0
            font.pixelSize: 20
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
        }
        Shape {
        // component (Instance) level: 0 Rectangle 5 
            id: figma_3_67
            // # "Rectangle 5"
            objectName:"Rectangle 5"
            x:0
            y:0
            width:309
            height:599
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ffe24747"
                // component (shapeFill) level: 0 
                id: svgpath_figma_3_67
                fillRule: ShapePath.WindingFill
                PathSvg {
                    id: path_0_figma_3_67
                    path: "M0 0L309 0L309 599L0 599L0 0Z"
                } 
            }
        property alias path: path_0_figma_3_67.path
        }
        Item {
        // component (Instance) level: 0 qml?subscriptions.asLoader 
            id: figma_3_68
            // # "qml?subscriptions.asLoader"
            objectName:"qml?subscriptions.asLoader"
            x: 24
            y: 57
            width:263
            height:243
                Loader {
                    id: l_figma_3_68
                    anchors.fill: parent
                    onLoaded: FigmaQmlSingleton.sourceLoaded('subscriptions')
                    onItemChanged: {if(!item) FigmaQmlSingleton.sourceError('subscriptions');}
                    Connections {
                        target: FigmaQmlSingleton
                        onSetSource: {
                            if(element == 'subscriptions')
                                l_figma_3_68.source = source;
                        }
                        onSetSourceComponent: {
                            if(element == 'subscriptions')
                                l_figma_3_68.sourceComponent = sourceComponent;
                        }
                    }
                }
        }
        Button8_figma {
        // component (Instance) level: 0 qml?remove.onClick 
            id: figma_3_88
            // # "qml?remove.onClick"
            objectName:"qml?remove.onClick"
            MouseArea {
                anchors.fill: parent
                onClicked: { FigmaQmlSingleton.eventReceived( 'remove', 'click_event' ); }
            }
            x:23
            y:391
            width:120
            height:45
            Shape {
            // component (Instance) level: 1 Rectangle 8 
                id: figma_i3_88_1_15
                // # "Rectangle 8"
                objectName:"Rectangle 8"
                x:0
                y:0
                width:120
                height:45
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffd9d9d9"
                    // component (shapeFill) level: 1 
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        id: path_0_figma_i3_88_1_15
                        path: "M0 0L120 0L120 45L0 45L0 0Z"
                    } 
                }
            property alias path: path_0_figma_i3_88_1_15.path
            }
            Text {
            // component (Instance) level: 1 Add file 
                id: figma_i3_88_1_17
                // # "Add file"
                objectName:"Add file"
                x:18
                y:14
                width:81.1111
                height:16
                color:"#ff000000"
                wrapMode: TextEdit.WordWrap
                text:"Unsubscribe"
                font.family: "DejaVu Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 13
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignVCenter
            }
        }
        Button8_figma {
        // component (Instance) level: 0 qml?publish_view.onClick 
            id: figma_3_72
            // # "qml?publish_view.onClick"
            objectName:"qml?publish_view.onClick"
            MouseArea {
                anchors.fill: parent
                onClicked: { FigmaQmlSingleton.eventReceived( 'publish_view', 'click_event' ); }
            }
            x:183
            y:26
            width:104
            height:20
            Shape {
            // component (Instance) level: 1 Rectangle 8 
                id: figma_i3_72_1_15
                // # "Rectangle 8"
                objectName:"Rectangle 8"
                x:0
                y:0
                width:104
                height:20
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffd9d9d9"
                    // component (shapeFill) level: 1 
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        id: path_0_figma_i3_72_1_15
                        path: "M0 0L104 0L104 20L0 20L0 0Z"
                    } 
                }
            property alias path: path_0_figma_i3_72_1_15.path
            }
            Text {
            // component (Instance) level: 1 Subscribe 
                id: figma_i3_72_1_17
                // # "Subscribe"
                objectName:"Subscribe"
                x:16
                y:2
                width:70.2963
                height:15
                color:"#ff000000"
                wrapMode: TextEdit.WordWrap
                text:"Publish"
                font.family: "DejaVu Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 12
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignVCenter
            }
        }
        Button8_figma {
        // component (Instance) level: 0 qml?subscribe.onClick 
            id: figma_3_73
            // # "qml?subscribe.onClick"
            objectName:"qml?subscribe.onClick"
            MouseArea {
                anchors.fill: parent
                onClicked: { FigmaQmlSingleton.eventReceived( 'subscribe', 'click_event' ); }
            }
            x:161
            y:391
            width:125
            height:45
            Shape {
            // component (Instance) level: 1 Rectangle 8 
                id: figma_i3_73_1_15
                // # "Rectangle 8"
                objectName:"Rectangle 8"
                x:0
                y:0
                width:125
                height:45
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffd9d9d9"
                    // component (shapeFill) level: 1 
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        id: path_0_figma_i3_73_1_15
                        path: "M0 0L125 0L125 45L0 45L0 0Z"
                    } 
                }
            property alias path: path_0_figma_i3_73_1_15.path
            }
            Text {
            // component (Instance) level: 1 Subscribe 
                id: figma_i3_73_1_17
                // # "Subscribe"
                objectName:"Subscribe"
                x:19
                y:14
                width:84.4907
                height:16
                color:"#ff000000"
                wrapMode: TextEdit.WordWrap
                text:"Subscribe"
                font.family: "DejaVu Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 13
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignVCenter
            }
        }
        Text {
        // component (Instance) level: 0 QMQTTI 
            id: figma_3_74
            // # "QMQTTI"
            objectName:"QMQTTI"
            x:24
            y:14
            width:159
            height:38
            color:"#ff000000"
            wrapMode: TextEdit.WordWrap
            text:"QMQTTI"
            font.family: "DejaVu Sans"
            font.italic: false
            font.letterSpacing: 0
            font.pixelSize: 20
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
        }
        Qml_server_address_onClick6_figma {
        // component (Instance) level: 0 qml?topic_subscribe.onClick 
            id: figma_3_97
            // # "qml?topic_subscribe.onClick"
            objectName:"qml?topic_subscribe.onClick"
            MouseArea {
                anchors.fill: parent
                onClicked: { FigmaQmlSingleton.eventReceived( 'topic_subscribe', 'click_event' ); }
            }
            x:23
            y:321
            Shape {
            // component (Instance) level: 1 Rectangle 8 
                id: figma_i3_97_3_93
                // # "Rectangle 8"
                objectName:"Rectangle 8"
                x:0
                y:1
                width:263
                height:48
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffd9d9d9"
                    // component (shapeFill) level: 1 
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        id: path_0_figma_i3_97_3_93
                        path: "M0 0L263 0L263 48L0 48L0 0Z"
                    } 
                }
            property alias path: path_0_figma_i3_97_3_93.path
            }
            Item {
            // component (Instance) level: 1 qml?topic_subscribe.asLoader 
                id: figma_i3_97_3_94
                // # "qml?topic_subscribe.asLoader"
                objectName:"qml?topic_subscribe.asLoader"
                Connections {
                    target: FigmaQmlSingleton
                    onValueChanged: {
                        switch(element) {
                        }
                    }
                }
                x: 0
                y: 0
                width:263
                height:49
                    Loader {
                        id: l_figma_i3_97_3_94
                        anchors.fill: parent
                        onLoaded: FigmaQmlSingleton.sourceLoaded('topic_subscribe')
                        onItemChanged: {if(!item) FigmaQmlSingleton.sourceError('topic_subscribe');}
                        Connections {
                            target: FigmaQmlSingleton
                            onSetSource: {
                                if(element == 'topic_subscribe')
                                    l_figma_i3_97_3_94.source = source;
                            }
                            onSetSourceComponent: {
                                if(element == 'topic_subscribe')
                                    l_figma_i3_97_3_94.sourceComponent = sourceComponent;
                            }
                        }
                    }
            }
        }
        Qml_server_address_onClick6_figma {
        // component (Instance) level: 0 qml?server_address.onClick 
            id: figma_7_111
            // # "qml?server_address.onClick"
            objectName:"qml?server_address.onClick"
            MouseArea {
                anchors.fill: parent
                onClicked: { FigmaQmlSingleton.eventReceived( 'server_address', 'click_event' ); }
            }
            x:23
            y:455
            Shape {
            // component (Instance) level: 1 Rectangle 8 
                id: figma_i7_111_3_93
                // # "Rectangle 8"
                objectName:"Rectangle 8"
                x:0
                y:1
                width:263
                height:48
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffd9d9d9"
                    // component (shapeFill) level: 1 
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        id: path_0_figma_i7_111_3_93
                        path: "M0 0L263 0L263 48L0 48L0 0Z"
                    } 
                }
            property alias path: path_0_figma_i7_111_3_93.path
            }
            Item {
            // component (Instance) level: 1 qml?server_address.asLoader 
                id: figma_i7_111_3_94
                // # "qml?server_address.asLoader"
                objectName:"qml?server_address.asLoader"
                Connections {
                    target: FigmaQmlSingleton
                    onValueChanged: {
                        switch(element) {
                        }
                    }
                }
                x: 0
                y: 0
                width:263
                height:49
                    Loader {
                        id: l_figma_i7_111_3_94
                        anchors.fill: parent
                        onLoaded: FigmaQmlSingleton.sourceLoaded('server_address')
                        onItemChanged: {if(!item) FigmaQmlSingleton.sourceError('server_address');}
                        Connections {
                            target: FigmaQmlSingleton
                            onSetSource: {
                                if(element == 'server_address')
                                    l_figma_i7_111_3_94.source = source;
                            }
                            onSetSourceComponent: {
                                if(element == 'server_address')
                                    l_figma_i7_111_3_94.sourceComponent = sourceComponent;
                            }
                        }
                    }
            }
        }
        Qml_server_address_onClick6_figma {
        // component (Instance) level: 0 qml?tag.onClick 
            id: figma_39_30
            // # "qml?tag.onClick"
            objectName:"qml?tag.onClick"
            visible: false
            MouseArea {
                anchors.fill: parent
                onClicked: { FigmaQmlSingleton.eventReceived( 'tag', 'click_event' ); }
            }
            x:24
            y:523
            width:263
            height:45
            Shape {
            // component (Instance) level: 1 Rectangle 8 
                id: figma_i39_30_3_93
                // # "Rectangle 8"
                objectName:"Rectangle 8"
                x:0
                y:0
                width:263
                height:44.0816
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffd9d9d9"
                    // component (shapeFill) level: 1 
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        id: path_0_figma_i39_30_3_93
                        path: "M0 0L263 0L263 44.0816L0 44.0816L0 0Z"
                    } 
                }
            property alias path: path_0_figma_i39_30_3_93.path
            }
            Item {
            // component (Instance) level: 1 qml?tag.asLoader 
                id: figma_i39_30_3_94
                // # "qml?tag.asLoader"
                objectName:"qml?tag.asLoader"
                Connections {
                    target: FigmaQmlSingleton
                    onValueChanged: {
                        switch(element) {
                        }
                    }
                }
                x: 0
                y: 0
                width:263
                height:45
                    Loader {
                        id: l_figma_i39_30_3_94
                        anchors.fill: parent
                        onLoaded: FigmaQmlSingleton.sourceLoaded('tag')
                        onItemChanged: {if(!item) FigmaQmlSingleton.sourceError('tag');}
                        Connections {
                            target: FigmaQmlSingleton
                            onSetSource: {
                                if(element == 'tag')
                                    l_figma_i39_30_3_94.source = source;
                            }
                            onSetSourceComponent: {
                                if(element == 'tag')
                                    l_figma_i39_30_3_94.sourceComponent = sourceComponent;
                            }
                        }
                    }
            }
        }
    }
    Connections {
        target: FigmaQmlSingleton
        onValueChanged: {
            switch(element) {
            }
        }
    }
}
